//APP ACTIONS
export const ACTIVATE_MOBILE_HEADER = "ACTIVATE_MOBILE_HEADER";
export const CHECK_DEVICE = "CHECK_DEVICE";
export const INIT = "INIT";
export const TOGGLE_FILTER_BAR = "TOGGLE_FILTER_BAR";
export const MOBILE_HEADER_ACTIVE = "MOBILE_HEADER_ACTIVE";

//AUTH ACTIONS
export const HANDLE_SIGNUP = "HANDLE_SIGNUP";
export const HANDLE_SUBMIT = "HANDLE_SUBMIT";

//CART ACTIONS
export const ADD_ITEM = "@@cart/ADD_ITEM";
export const CALCULATE_SUBTOTAL = "CALCULATE_SUBTOTAL";
export const CHANGE_FILTER = "CHANGE_FILTER";
export const CHANGE_QUANTITY = "CHANGE_QUANTITY";
export const CHECKOUT = "CHECKOUT";

//CART: AUTO DELETE WHEN QUANTITY IS 0
export const CHECK_DELETE = "CHECK_DELETE";
export const CONFIRM_DELETE = "@@cart/CONFIRM_DELETE";
export const REJECT_DELETE = "@@cart/REJECT_DELETE";

//CART: MODAL
export const SHOW_MODAL = "SHOW_MODAL";

export const HANDLE_CART_CLICK = "HANDLE_CART_CLICK";
export const NEW_FILTER = "NEW_FILTER";
export const REMOVE_ITEM = "@@cart/REMOVE_ITEM";
export const UPDATE_QUANTITY = "@@cart/UPDATE_QUANTITY";
export const UPDATE_SUBTOTAL = "UPDATE_SUBTOTAL";
export const UPDATE_SUBTOTAL_FAILED = "UPDATE_SUBTOTAL_FAILED";

//INSTAGRAM IMAGES
export const CREATE_PRODUCT_FROM_IMAGE = "CREATE_PRODUCT_FROM_IMAGE";

export const ADD_TO_CART = "@@cart/ADD_TO_CART";
export const CART = "CART";
export const REMOVE_FROM_CART = "@@cart/REMOVE_FROM_CART";

export const GET_RECENT_IMAGES_PENDING = "GET_RECENT_IMAGES_PENDING";
export const GET_RECENT_IMAGES_FULFILLED = "GET_RECENT_IMAGES_FULFILLED";
export const GET_RECENT_IMAGES_REJECTED = "GET_RECENT_IMAGES_REJECTED";

export const SORT_IMAGES_PENDING = "SORT_IMAGES_PENDING";
export const SORT_IMAGES_FULFILLED = "SORT_IMAGES_FULFILLED";

//FORMS
export const EMAIL_IN_USE = "EMAIL_IN_USE";
export const FORM_ERROR = "FORM_ERROR";
export const ROUTE_AND_AUTOFILL = "ROUTE_AND_AUTOFILL";
export const SUBMIT_SIGN_IN = "SUBMIT_SIGN_IN";
export const SUBMIT_SIGN_OUT = "SUBMIT_SIGN_OUT";
export const SUBMIT_USER_DATA = "SUBMIT_USER_DATA";
export const UPDATE_USER = "UPDATE_USER";

//USER
export const SET_USER_DATA = "SET_USER_DATA";
export const RESET_USER_DATA = "RESET_USER_DATA";
export const SET_USER_ERROR_DATA = "SET_USER_ERROR_DATA";
